### ISSUE TITLE
Development: 파일명 변경

### ISSUE THREAD

**Issue by se0kjun** [drzix/z-Chrome#13]
일반적으로 background.js파일은 chrome extension에서 [다른의미로 사용됨](https://developer.chrome.com/extensions/background_pages)
그래서 현재 사용중인 background.js파일은 일반적으로 chrome extension에서 popup.js로 바꾸는게 어떨지..

**Comment by kyeongmincho** [comment]
처음 시작을 백그라운드로 시작하여 그렇게 되었는데 이제 팝업으로 바뀌게 되었으니
popup.js로 바꿔도 된다고 생각하는 부분이다.
https://github.com/drzix/z-Chrome/blob/master/html/popup.html#L20 도 추가로 수정해야 할 것:)
