### ISSUE TITLE
Development: tab(\t)말고 4 space 사용

### ISSUE THREAD

**Issue by yumere** [drzix/z-Chrome#16]
@se0kjun 이 지금 \t 를 사용하고 있는 것 같은데, 전부 4 space로 통일하자.

\t 문자는 각 에디터 혹은 IDE에서 다르게 인식할 가능성이 존재함

**Comment by se0kjun** [comment]
:+1:

**Comment by kyeongmincho** [comment]
나는 지금 아톰으로 4space설정하고 탭을 누르고 있는데 이건 어떻게 되는거지? 제대로 되는건가

**Comment by yumere** [comment]
@drzix 4space 하고 탭 하는거면 원래 적용돼야 하는 건데, 확인해보려면 tab해서 방향키로 한칸 씩 움직여지면 제대로 적용 된 것 :+1:

**Comment by yumere** [comment]
:+1:
